<a href="https://colab.research.google.com/github/devisravani5C4/Cybersecurity-Projects/blob/main/Copy_of_CybersecurityProjectLSB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import cv2

In [ ]:
#characters to ascii values and vice versa
ca={chr(i):i for i in range(255)}
ac={i:chr(i) for i in range(255)}

In [ ]:
print(ca)
print(ac)

{'\x00': 0, '\x01': 1, '\x02': 2, '\x03': 3, '\x04': 4, '\x05': 5, '\x06': 6, '\x07': 7, '\x08': 8, '\t': 9, '\n': 10, '\x0b': 11, '\x0c': 12, '\r': 13, '\x0e': 14, '\x0f': 15, '\x10': 16, '\x11': 17, '\x12': 18, '\x13': 19, '\x14': 20, '\x15': 21, '\x16': 22, '\x17': 23, '\x18': 24, '\x19': 25, '\x1a': 26, '\x1b': 27, '\x1c': 28, '\x1d': 29, '\x1e': 30, '\x1f': 31, ' ': 32, '!': 33, '"': 34, '#': 35, '$': 36, '%': 37, '&': 38, "'": 39, '(': 40, ')': 41, '*': 42, '+': 43, ',': 44, '-': 45, '.': 46, '/': 47, '0': 48, '1': 49, '2': 50, '3': 51, '4': 52, '5': 53, '6': 54, '7': 55, '8': 56, '9': 57, ':': 58, ';': 59, '<': 60, '=': 61, '>': 62, '?': 63, '@': 64, 'A': 65, 'B': 66, 'C': 67, 'D': 68, 'E': 69, 'F': 70, 'G': 71, 'H': 72, 'I': 73, 'J': 74, 'K': 75, 'L': 76, 'M': 77, 'N': 78, 'O': 79, 'P': 80, 'Q': 81, 'R': 82, 'S': 83, 'T': 84, 'U': 85, 'V': 86, 'W': 87, 'X': 88, 'Y': 89, 'Z': 90, '[': 91, '\\': 92, ']': 93, '^': 94, '_': 95, '`': 96, 'a': 97, 'b': 98, 'c': 99, 'd': 100, 'e': 101

Defining the key and message:-

In [ ]:
text="hello"
key="123"

In [ ]:
#random pixel value image

x=np.random.randint(0,255,(10,10,3),dtype=np.uint8)

In [ ]:
x

array([[[ 16,   4, 185],
        [ 69, 155,  55],
        [ 53, 226,  62],
        [130, 140,  68],
        [ 75, 165, 199],
        [154,  24, 252],
        [ 87,  38,  24],
        [ 71,   6, 143],
        [ 13,  74, 182],
        [ 15,  23,  95]],

       [[ 59, 176,   4],
        [186,  85, 163],
        [ 47, 211, 250],
        [ 38,  56, 108],
        [ 94, 173, 115],
        [137,  41, 140],
        [126, 133, 115],
        [ 19, 243,  41],
        [192, 143, 114],
        [113, 179, 253]],

       [[214, 248,  40],
        [ 18, 202, 136],
        [151,   9,   2],
        [116,  85,  56],
        [  3,  38, 109],
        [155, 147, 253],
        [ 29,  29,   9],
        [222,  18, 140],
        [189,  41,  77],
        [  1, 164,  95]],

       [[128,   2, 154],
        [207,  99, 187],
        [233,  82, 202],
        [124,  66,  21],
        [215, 124, 241],
        [229,  34,  63],
        [188,  78, 172],
        [  9,  57, 241],
        [178, 100, 154],
        [ 63, 184, 253]],

       [[197, 177, 222],
        [150, 163,  29],
        [ 40,  11,  75],
        [ 18, 246, 184],
        [ 22, 171,  31],
        [204,  60,  15],
        [  9, 226, 166],
        [199,  57,  11],
        [182, 155, 171],
        [154,  48,  90]],

       [[125, 130,  45],
        [  7,  10, 217],
        [238, 226, 235],
        [217, 147,  39],
        [160, 106, 221],
        [  5, 170, 129],
        [138, 101,  99],
        [240, 130, 226],
        [114,  85,  40],
        [ 82, 206,  27]],

       [[153, 198,  52],
        [ 70, 117, 175],
        [135,   4,  19],
        [  6, 103, 127],
        [156, 219, 194],
        [159, 196, 204],
        [206,  71, 137],
        [189, 224,  34],
        [ 41, 134,  73],
        [ 29, 226, 202]],

       [[246, 114, 173],
        [  9,  48, 176],
        [229,  54, 209],
        [136, 131, 101],
        [174,  53,  54],
        [230, 190,  27],
        [ 32,  57,  45],
        [236, 210, 158],
        [ 67, 200,  99],
        [220,  52, 211]],

       [[ 16,  78, 247],
        [196,  15,  53],
        [204,  20, 249],
        [ 15,  85, 106],
        [181, 139,  68],
        [  2, 248, 114],
        [209,  79, 174],
        [  6, 196, 205],
        [ 23,  52,  49],
        [152, 133, 192]],

       [[139,  56,  69],
        [ 48, 220,  84],
        [216, 151, 176],
        [110, 141, 190],
        [202,   3, 196],
        [248,  39, 180],
        [ 53, 241, 159],
        [142, 197,  78],
        [ 41, 178, 224],
        [234, 252, 213]]], dtype=uint8)

This is my cover image.

In [ ]:
x.shape

(10, 10, 3)

In [ ]:
text_ascii=[ca[ch] for ch in text]
key_ascii=[ca[ch] for ch in key]

In [ ]:
print(text,"=",text_ascii)

print(key,"=",key_ascii)

hello = [104, 101, 108, 108, 111]
123 = [49, 50, 51]


ENCRYPTION:-(Hiding message into cover image)

In [ ]:
x_enc=x.copy()
n,m,z=0,0,0
l=len(text)
kl=0
for i in range(l):
  char_val=ca[text[i]]^ca[key[kl]]
  for bit_pos in range(8):
     bit=(char_val >> (7-bit_pos))&1
     org_val=x_enc[n,m,z]
     x_enc[n,m,z]=(org_val & 0xFE)|bit

     print("original value is ",org_val," after embedding bit ",bit ," at pixel (",n,m,z,") of ",text[i]," the new value is ",x_enc[n,m,z])
     z=(z+1)%3
     if z==0:
       m=m+1
       if m==x_enc.shape[1]:
          m=0
          n=n+1
  kl=(kl+1)%len(key)

original value is  16  after embedding bit  0  at pixel ( 0 0 0 ) of  h  the new value is  16
original value is  4  after embedding bit  1  at pixel ( 0 0 1 ) of  h  the new value is  5
original value is  185  after embedding bit  0  at pixel ( 0 0 2 ) of  h  the new value is  184
original value is  69  after embedding bit  1  at pixel ( 0 1 0 ) of  h  the new value is  69
original value is  155  after embedding bit  1  at pixel ( 0 1 1 ) of  h  the new value is  155
original value is  55  after embedding bit  0  at pixel ( 0 1 2 ) of  h  the new value is  54
original value is  53  after embedding bit  0  at pixel ( 0 2 0 ) of  h  the new value is  52
original value is  226  after embedding bit  1  at pixel ( 0 2 1 ) of  h  the new value is  227
original value is  62  after embedding bit  0  at pixel ( 0 2 2 ) of  e  the new value is  62
original value is  130  after embedding bit  1  at pixel ( 0 3 0 ) of  e  the new value is  131
original value is  140  after embedding bit  0  at pix

In [ ]:
x_enc

array([[[ 16,   5, 184],
        [ 69, 155,  54],
        [ 52, 227,  62],
        [131, 140,  69],
        [ 74, 165, 199],
        [155,  24, 253],
        [ 86,  39,  25],
        [ 71,   7, 143],
        [ 12,  75, 182],
        [ 15,  23,  95]],

       [[ 58, 177,   4],
        [187,  84, 163],
        [ 47, 211, 250],
        [ 39,  56, 108],
        [ 94, 173, 115],
        [137,  41, 140],
        [126, 133, 115],
        [ 19, 243,  41],
        [192, 143, 114],
        [113, 179, 253]],

       [[214, 248,  40],
        [ 18, 202, 136],
        [151,   9,   2],
        [116,  85,  56],
        [  3,  38, 109],
        [155, 147, 253],
        [ 29,  29,   9],
        [222,  18, 140],
        [189,  41,  77],
        [  1, 164,  95]],

       [[128,   2, 154],
        [207,  99, 187],
        [233,  82, 202],
        [124,  66,  21],
        [215, 124, 241],
        [229,  34,  63],
        [188,  78, 172],
        [  9,  57, 241],
        [178, 100, 154],
        [ 63, 184, 253]],

       [[197, 177, 222],
        [150, 163,  29],
        [ 40,  11,  75],
        [ 18, 246, 184],
        [ 22, 171,  31],
        [204,  60,  15],
        [  9, 226, 166],
        [199,  57,  11],
        [182, 155, 171],
        [154,  48,  90]],

       [[125, 130,  45],
        [  7,  10, 217],
        [238, 226, 235],
        [217, 147,  39],
        [160, 106, 221],
        [  5, 170, 129],
        [138, 101,  99],
        [240, 130, 226],
        [114,  85,  40],
        [ 82, 206,  27]],

       [[153, 198,  52],
        [ 70, 117, 175],
        [135,   4,  19],
        [  6, 103, 127],
        [156, 219, 194],
        [159, 196, 204],
        [206,  71, 137],
        [189, 224,  34],
        [ 41, 134,  73],
        [ 29, 226, 202]],

       [[246, 114, 173],
        [  9,  48, 176],
        [229,  54, 209],
        [136, 131, 101],
        [174,  53,  54],
        [230, 190,  27],
        [ 32,  57,  45],
        [236, 210, 158],
        [ 67, 200,  99],
        [220,  52, 211]],

       [[ 16,  78, 247],
        [196,  15,  53],
        [204,  20, 249],
        [ 15,  85, 106],
        [181, 139,  68],
        [  2, 248, 114],
        [209,  79, 174],
        [  6, 196, 205],
        [ 23,  52,  49],
        [152, 133, 192]],

       [[139,  56,  69],
        [ 48, 220,  84],
        [216, 151, 176],
        [110, 141, 190],
        [202,   3, 196],
        [248,  39, 180],
        [ 53, 241, 159],
        [142, 197,  78],
        [ 41, 178, 224],
        [234, 252, 213]]], dtype=uint8)

In [ ]:
cv2.cvtColor(x_enc,cv2.COLOR_BGR2RGB)

array([[[184,   5,  16],
        [ 54, 155,  69],
        [ 62, 227,  52],
        [ 69, 140, 131],
        [199, 165,  74],
        [253,  24, 155],
        [ 25,  39,  86],
        [143,   7,  71],
        [182,  75,  12],
        [ 95,  23,  15]],

       [[  4, 177,  58],
        [163,  84, 187],
        [250, 211,  47],
        [108,  56,  39],
        [115, 173,  94],
        [140,  41, 137],
        [115, 133, 126],
        [ 41, 243,  19],
        [114, 143, 192],
        [253, 179, 113]],

       [[ 40, 248, 214],
        [136, 202,  18],
        [  2,   9, 151],
        [ 56,  85, 116],
        [109,  38,   3],
        [253, 147, 155],
        [  9,  29,  29],
        [140,  18, 222],
        [ 77,  41, 189],
        [ 95, 164,   1]],

       [[154,   2, 128],
        [187,  99, 207],
        [202,  82, 233],
        [ 21,  66, 124],
        [241, 124, 215],
        [ 63,  34, 229],
        [172,  78, 188],
        [241,  57,   9],
        [154, 100, 178],
        [253, 184,  63]],

       [[222, 177, 197],
        [ 29, 163, 150],
        [ 75,  11,  40],
        [184, 246,  18],
        [ 31, 171,  22],
        [ 15,  60, 204],
        [166, 226,   9],
        [ 11,  57, 199],
        [171, 155, 182],
        [ 90,  48, 154]],

       [[ 45, 130, 125],
        [217,  10,   7],
        [235, 226, 238],
        [ 39, 147, 217],
        [221, 106, 160],
        [129, 170,   5],
        [ 99, 101, 138],
        [226, 130, 240],
        [ 40,  85, 114],
        [ 27, 206,  82]],

       [[ 52, 198, 153],
        [175, 117,  70],
        [ 19,   4, 135],
        [127, 103,   6],
        [194, 219, 156],
        [204, 196, 159],
        [137,  71, 206],
        [ 34, 224, 189],
        [ 73, 134,  41],
        [202, 226,  29]],

       [[173, 114, 246],
        [176,  48,   9],
        [209,  54, 229],
        [101, 131, 136],
        [ 54,  53, 174],
        [ 27, 190, 230],
        [ 45,  57,  32],
        [158, 210, 236],
        [ 99, 200,  67],
        [211,  52, 220]],

       [[247,  78,  16],
        [ 53,  15, 196],
        [249,  20, 204],
        [106,  85,  15],
        [ 68, 139, 181],
        [114, 248,   2],
        [174,  79, 209],
        [205, 196,   6],
        [ 49,  52,  23],
        [192, 133, 152]],

       [[ 69,  56, 139],
        [ 84, 220,  48],
        [176, 151, 216],
        [190, 141, 110],
        [196,   3, 202],
        [180,  39, 248],
        [159, 241,  53],
        [ 78, 197, 142],
        [224, 178,  41],
        [213, 252, 234]]], dtype=uint8)

Now this is my stego-object (cover+text message)

It is ready at sender side

DECRYPTION:-

(at reciever side, the stegno-object is recieved . Now we have to decrypt the image and get the actual text message as shown below.)

In [ ]:
n,m,z=0,0,0
kl=0
decrypt_msg=""
for i in range(l):
  value=0
  for bit_pos in range(8):
    bit=x_enc[n,m,z] & 1
    value=(value << 1)| bit
    print("Reading bit ",bit," from pixel (",n,m,z,")")
    z=(z+1)%3
    if z==0:
      m=m+1
      if m==x_enc.shape[1]:
         m=0
         n=n+1

  org_char=ac[value ^ ca[key[kl]]]
  print("decrypted value =",value," XOR ",ca[key[kl]]," =",value^ca[key[kl]]," i e., ",org_char)
  decrypt_msg=decrypt_msg+org_char
  kl=(kl+1)%len(key)

print(decrypt_msg)

Reading bit  0  from pixel ( 0 0 0 )
Reading bit  1  from pixel ( 0 0 1 )
Reading bit  0  from pixel ( 0 0 2 )
Reading bit  1  from pixel ( 0 1 0 )
Reading bit  1  from pixel ( 0 1 1 )
Reading bit  0  from pixel ( 0 1 2 )
Reading bit  0  from pixel ( 0 2 0 )
Reading bit  1  from pixel ( 0 2 1 )
decrypted value = 89  XOR  49  = 104  i e.,  h
Reading bit  0  from pixel ( 0 2 2 )
Reading bit  1  from pixel ( 0 3 0 )
Reading bit  0  from pixel ( 0 3 1 )
Reading bit  1  from pixel ( 0 3 2 )
Reading bit  0  from pixel ( 0 4 0 )
Reading bit  1  from pixel ( 0 4 1 )
Reading bit  1  from pixel ( 0 4 2 )
Reading bit  1  from pixel ( 0 5 0 )
decrypted value = 87  XOR  50  = 101  i e.,  e
Reading bit  0  from pixel ( 0 5 1 )
Reading bit  1  from pixel ( 0 5 2 )
Reading bit  0  from pixel ( 0 6 0 )
Reading bit  1  from pixel ( 0 6 1 )
Reading bit  1  from pixel ( 0 6 2 )
Reading bit  1  from pixel ( 0 7 0 )
Reading bit  1  from pixel ( 0 7 1 )
Reading bit  1  from pixel ( 0 7 2 )
decrypted value = 